-- ─── which shops carry these, by name ────────────────────────────────────────
-- A shopping list row knows a name and a maker and nothing else. It is a row in
-- the APP's database, written when somebody added it, and it has no idea the
-- catalog exists -- which is correct, and is why a list still works with no
-- catalog configured at all.
--
-- So showing which shop a listed product came from needs a lookup, and a lookup
-- for a whole list at once rather than one per row: a list of twenty items would
-- otherwise be twenty round trips on every load.
--
-- WHY NOT search_catalog. It is a ranked text search built to answer a
-- half-typed word with the best few matches. This is the opposite question --
-- exact names, all of them, no ranking -- and asking a search engine for an
-- exact match twenty times is both slower and less accurate than asking for the
-- rows themselves.
--
-- WHY NOT A COLUMN ON THE APP'S shopping_items. Because it would be a copy that
-- goes stale the moment a shop drops the product, and because the two databases
-- are deliberately not joined: the app's list survives the catalog being
-- unreachable, and a column would make that survival a lie.
--
-- Matching mirrors bump_product_popularity: the folded canonical name first,
-- then the folded name a RETAILER used, because the row on the list was very
-- often picked out of a dropdown showing a shop's own wording rather than ours.
-- catalog_shops_for LIVES IN 009, ALONE. It was defined here first; 009 gave it
-- a total sort key, because the indexes added there changed the plan and with it
-- which of several tied products won -- so the same shopping list started
-- reporting a different maker for a row.
--
-- The definition did not stay here as well. Two files restating one function is a
-- race whose winner is whichever was pushed last, and the loss is silent: see the
-- note in 003, where exactly that happened to catalog_run_open and stopped
-- abandoned scrape runs being closed for three days.
--
-- What this file is for is the reasoning above, which is about the SHAPE of the
-- lookup rather than its body, and which nothing in 009 repeats.
